# Site settings
# theme: jekyll-theme-minimal
title: Camille et Maxime 2023
email: t-vdcx+mariage@pm.me
url: https://127.0.0.1
description: "Mariage le 1er juin 2023"

# Color settings (hex-codes without the leading hash-tag)
color:
  background: '#ffffff'
  primary: '#6750A4'
  primary-container: '#EADDFF'
  secondary: '#625B71'
  secondary-container: '#E8DEF8'
  tertiary: '#7D5260'
  tertiary-container: '#FFD8E4'

# Footer settings
footer: Maxime Londéchal

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/pjb5c
# Build settings
markdown: kramdown
permalink: pretty
